ImageGallery.BFF/Models/ErrorViewModel.cs
namespace ImageGallery.BFF.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ImageGallery.BFF/Controllers/HomeController.cs
using ImageGallery.BFF.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ImageGallery.BFF.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        [Authorize]
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ImageGallery.BFF/Controllers/UserSessionController.cs
using IdentityModel.Client;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Protocols.OpenIdConnect;

namespace ImageGallery.BFF.Controllers
{
    [Authorize]
    public class UserSessionController : Controller
    {
        private readonly IHttpClientFactory _httpClientFactory;

        public UserSessionController(IHttpClientFactory httpClientFactory)
        {
            _httpClientFactory = httpClientFactory;
        }

        public IActionResult GivenName()
        {
            var objectToReturn = new
            {
                given_name = User.Claims.FirstOrDefault(c => c.Type == "given_name")?.Value
            };

            return Json(objectToReturn);
        }

        public async Task LogoutUser()
        {
            var client = _httpClientFactory.CreateClient("IDPClient");
            var discoveryDocumentResponse = await client.GetDiscoveryDocumentAsync();
            if (discoveryDocumentResponse.IsError)
            {
                throw new Exception(discoveryDocumentResponse.Error);
            }

            var accessTokenRevocationResponse = await client.RevokeTokenAsync(new()
            {
                Address = discoveryDocumentResponse.RevocationEndpoint,
                ClientId = "imagegallerybff",
                ClientSecret = "bffsecret",
                Token = await HttpContext.GetTokenAsync(OpenIdConnectParameterNames.AccessToken),
            });

            if (accessTokenRevocationResponse.IsError)
            {
                throw new Exception(accessTokenRevocationResponse.Error);
            }

            var refreshTokenRevocationResponse = await client.RevokeTokenAsync(new()
            {
                Address = discoveryDocumentResponse.RevocationEndpoint,
                ClientId = "imagegallerybff",
                ClientSecret = "bffsecret",
                Token = await HttpContext.GetTokenAsync(OpenIdConnectParameterNames.RefreshToken),
            });

            if (refreshTokenRevocationResponse.IsError)
            {
                throw new Exception(refreshTokenRevocationResponse.Error);
            }
            await HttpContext.SignOutAsync("BffCookieScheme");
            await HttpContext.SignOutAsync("BffChallengeScheme");
        }
    }
}

ImageGallery.BFF/Views/Home/Index.cshtml
<script>
    fetch('/bff/images')
        .then((response) => response.json())
        .then((images) => {
            const container = document.getElementById('container_for_images');

            for (let i = 0; i < images.length; i++) {
                const surroundingDiv = document.createElement('div');
                surroundingDiv.className = 'pull-left col-md-4';

                const firstInnerDiv = document.createElement('div');
                const img = document.createElement('img');
                img.className = 'thumbnailImage';
                img.src = 'https://localhost:7075/images/' + images[i].FileName;

                firstInnerDiv.appendChild(img);
                surroundingDiv.appendChild(firstInnerDiv);

                const secondInnerDiv = document.createElement('div');
                const titleDiv = document.createElement('div');
                titleDiv.className = 'h6 topMarginSmall';
                titleDiv.innerHTML = images[i].Title;
                secondInnerDiv.appendChild(titleDiv);

                surroundingDiv.appendChild(secondInnerDiv);
                container.appendChild(surroundingDiv);
            }
        }).catch(console.error);
</script>

<div class="bottomMarginDefault">
</div>

<div class="container">
    <div class="row" id="container_for_images">
    </div>
</div> 

ImageGallery.BFF/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ImageGallery.BFF</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ImageGallery.BFF.styles.css" asp-append-version="true" />

    <script>
        fetch('usersession/givenname').then(
            (response) => response.json())
            .then((responseAsJson) => {
                var logoutButton = document.getElementById('logout-button');
                logoutButton.innerHTML = 'Logout (' + responseAsJson.given_name + ')';
            })
            .catch(console.error);

    </script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ImageGallery.BFF</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" id="logout-button" asp-area="" asp-controller="UserSession" asp-action="LogoutUser">Logout</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - ImageGallery.BFF - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>